list(APPEND ICONS_SRC
    materialindex.theme
    materialsvg/3d-rotation.svg
    materialsvg/access-alarms.svg
    materialsvg/access-alarm.svg
    materialsvg/accessibility.svg
    materialsvg/accessible.svg
    materialsvg/access-time.svg
    materialsvg/account-balance.svg
    materialsvg/account-balance-wallet.svg
    materialsvg/account-box.svg
    materialsvg/account-circle.svg
    materialsvg/ac-unit.svg
    materialsvg/adb.svg
    materialsvg/add-alarm.svg
    materialsvg/add-alert.svg
    materialsvg/add-box.svg
    materialsvg/add-circle-outline.svg
    materialsvg/add-circle.svg
    materialsvg/add-location.svg
    materialsvg/add-shopping-cart.svg
    materialsvg/add.svg
    materialsvg/add-to-photos.svg
    materialsvg/add-to-queue.svg
    materialsvg/adjust.svg
    materialsvg/airline-seat-flat-angled.svg
    materialsvg/airline-seat-flat.svg
    materialsvg/airline-seat-individual-suite.svg
    materialsvg/airline-seat-legroom-extra.svg
    materialsvg/airline-seat-legroom-normal.svg
    materialsvg/airline-seat-legroom-reduced.svg
    materialsvg/airline-seat-recline-extra.svg
    materialsvg/airline-seat-recline-normal.svg
    materialsvg/airplanemode-active.svg
    materialsvg/airplanemode-inactive.svg
    materialsvg/airplay.svg
    materialsvg/airport-shuttle.svg
    materialsvg/alarm-add.svg
    materialsvg/alarm-off.svg
    materialsvg/alarm-on.svg
    materialsvg/alarm.svg
    materialsvg/album.svg
    materialsvg/all-inclusive.svg
    materialsvg/all-out.svg
    materialsvg/android.svg
    materialsvg/announcement.svg
    materialsvg/apps.svg
    materialsvg/archive.svg
    materialsvg/arrow-back.svg
    materialsvg/arrow-downward.svg
    materialsvg/arrow-drop-down-circle.svg
    materialsvg/arrow-drop-down.svg
    materialsvg/arrow-drop-up.svg
    materialsvg/arrow-forward.svg
    materialsvg/arrow-upward.svg
    materialsvg/art-track.svg
    materialsvg/aspect-ratio.svg
    materialsvg/assessment.svg
    materialsvg/assignment-ind.svg
    materialsvg/assignment-late.svg
    materialsvg/assignment-returned.svg
    materialsvg/assignment-return.svg
    materialsvg/assignment.svg
    materialsvg/assignment-turned-in.svg
    materialsvg/assistant-photo.svg
    materialsvg/assistant.svg
    materialsvg/attach-file.svg
    materialsvg/attachment.svg
    materialsvg/attach-money.svg
    materialsvg/audiotrack.svg
    materialsvg/autorenew.svg
    materialsvg/av-timer.svg
    materialsvg/backspace.svg
    materialsvg/backup.svg
    materialsvg/battery-20.svg
    materialsvg/battery-30.svg
    materialsvg/battery-50.svg
    materialsvg/battery-60.svg
    materialsvg/battery-80.svg
    materialsvg/battery-90.svg
    materialsvg/battery-alert.svg
    materialsvg/battery-charging-20.svg
    materialsvg/battery-charging-30.svg
    materialsvg/battery-charging-50.svg
    materialsvg/battery-charging-60.svg
    materialsvg/battery-charging-80.svg
    materialsvg/battery-charging-90.svg
    materialsvg/battery-charging-full.svg
    materialsvg/battery-full.svg
    materialsvg/battery-std.svg
    materialsvg/battery-unknown.svg
    materialsvg/beach-access.svg
    materialsvg/beenhere.svg
    materialsvg/block.svg
    materialsvg/bluetooth-audio.svg
    materialsvg/bluetooth-connected.svg
    materialsvg/bluetooth-disabled.svg
    materialsvg/bluetooth-searching.svg
    materialsvg/bluetooth.svg
    materialsvg/blur-circular.svg
    materialsvg/blur-linear.svg
    materialsvg/blur-off.svg
    materialsvg/blur-on.svg
    materialsvg/bookmark-border.svg
    materialsvg/bookmark.svg
    materialsvg/book.svg
    materialsvg/border-all.svg
    materialsvg/border-bottom.svg
    materialsvg/border-clear.svg
    materialsvg/border-color.svg
    materialsvg/border-horizontal.svg
    materialsvg/border-inner.svg
    materialsvg/border-left.svg
    materialsvg/border-outer.svg
    materialsvg/border-right.svg
    materialsvg/border-style.svg
    materialsvg/border-top.svg
    materialsvg/border-vertical.svg
    materialsvg/branding-watermark.svg
    materialsvg/brightness-1.svg
    materialsvg/brightness-2.svg
    materialsvg/brightness-3.svg
    materialsvg/brightness-4.svg
    materialsvg/brightness-5.svg
    materialsvg/brightness-6.svg
    materialsvg/brightness-7.svg
    materialsvg/brightness-auto.svg
    materialsvg/brightness-high.svg
    materialsvg/brightness-low.svg
    materialsvg/brightness-medium.svg
    materialsvg/broken-image.svg
    materialsvg/brush.svg
    materialsvg/bubble-chart.svg
    materialsvg/bug-report.svg
    materialsvg/build.svg
    materialsvg/burst-mode.svg
    materialsvg/business-center.svg
    materialsvg/business.svg
    materialsvg/cached.svg
    materialsvg/cake.svg
    materialsvg/call-end.svg
    materialsvg/call-made.svg
    materialsvg/call-merge.svg
    materialsvg/call-missed-outgoing.svg
    materialsvg/call-missed.svg
    materialsvg/call-received.svg
    materialsvg/call-split.svg
    materialsvg/call.svg
    materialsvg/call-to-action.svg
    materialsvg/camera-alt.svg
    materialsvg/camera-front.svg
    materialsvg/camera-rear.svg
    materialsvg/camera-roll.svg
    materialsvg/camera.svg
    materialsvg/cancel.svg
    materialsvg/card-giftcard.svg
    materialsvg/card-membership.svg
    materialsvg/card-travel.svg
    materialsvg/casino.svg
    materialsvg/cast-connected.svg
    materialsvg/cast.svg
    materialsvg/center-focus-strong.svg
    materialsvg/center-focus-weak.svg
    materialsvg/change-history.svg
    materialsvg/chat-bubble-outline.svg
    materialsvg/chat-bubble.svg
    materialsvg/chat.svg
    materialsvg/check-box-outline-blank.svg
    materialsvg/check-box.svg
    materialsvg/check-circle.svg
    materialsvg/check.svg
    materialsvg/chevron-left.svg
    materialsvg/chevron-right.svg
    materialsvg/child-care.svg
    materialsvg/child-friendly.svg
    materialsvg/chrome-reader-mode.svg
    materialsvg/class.svg
    materialsvg/clear-all.svg
    materialsvg/clear.svg
    materialsvg/closed-caption.svg
    materialsvg/close.svg
    materialsvg/cloud-circle.svg
    materialsvg/cloud-done.svg
    materialsvg/cloud-download.svg
    materialsvg/cloud-off.svg
    materialsvg/cloud-queue.svg
    materialsvg/cloud.svg
    materialsvg/cloud-upload.svg
    materialsvg/code.svg
    materialsvg/collections.svg
    materialsvg/colorize.svg
    materialsvg/color-lens.svg
    materialsvg/comment.svg
    materialsvg/compare-arrows.svg
    materialsvg/compare.svg
    materialsvg/computer.svg
    materialsvg/confirmation-number.svg
    materialsvg/contact-mail.svg
    materialsvg/contact-phone.svg
    materialsvg/contacts.svg
    materialsvg/content-copy.svg
    materialsvg/content-cut.svg
    materialsvg/content-paste.svg
    materialsvg/control-point-duplicate.svg
    materialsvg/control-point.svg
    materialsvg/copyright.svg
    materialsvg/create-new-folder.svg
    materialsvg/create.svg
    materialsvg/credit-card.svg
    materialsvg/crop-16-9.svg
    materialsvg/crop-3-2.svg
    materialsvg/crop-5-4.svg
    materialsvg/crop-7-5.svg
    materialsvg/crop-din.svg
    materialsvg/crop-free.svg
    materialsvg/crop-landscape.svg
    materialsvg/crop-original.svg
    materialsvg/crop-portrait.svg
    materialsvg/crop-rotate.svg
    materialsvg/crop-square.svg
    materialsvg/crop.svg
    materialsvg/dashboard.svg
    materialsvg/data-usage.svg
    materialsvg/date-range.svg
    materialsvg/dehaze.svg
    materialsvg/delete-forever.svg
    materialsvg/delete.svg
    materialsvg/delete-sweep.svg
    materialsvg/description.svg
    materialsvg/desktop-mac.svg
    materialsvg/desktop-windows.svg
    materialsvg/details.svg
    materialsvg/developer-board.svg
    materialsvg/developer-mode.svg
    materialsvg/devices-other.svg
    materialsvg/devices.svg
    materialsvg/dialer-sip.svg
    materialsvg/dialpad.svg
    materialsvg/directions-bike.svg
    materialsvg/directions-boat.svg
    materialsvg/directions-bus.svg
    materialsvg/directions-car.svg
    materialsvg/directions-railway.svg
    materialsvg/directions-run.svg
    materialsvg/directions-subway.svg
    materialsvg/directions.svg
    materialsvg/directions-transit.svg
    materialsvg/directions-walk.svg
    materialsvg/disc-full.svg
    materialsvg/dns.svg
    materialsvg/dock.svg
    materialsvg/domain.svg
    materialsvg/done-all.svg
    materialsvg/done.svg
    materialsvg/do-not-disturb-alt.svg
    materialsvg/do-not-disturb-off.svg
    materialsvg/do-not-disturb-on.svg
    materialsvg/do-not-disturb.svg
    materialsvg/donut-large.svg
    materialsvg/donut-small.svg
    materialsvg/drafts.svg
    materialsvg/drag-handle.svg
    materialsvg/drag-indicator.svg
    materialsvg/drive-eta.svg
    materialsvg/dvr.svg
    materialsvg/edit-location.svg
    materialsvg/edit.svg
    materialsvg/email.svg
    materialsvg/enhanced-encryption.svg
    materialsvg/equalizer.svg
    materialsvg/error-outline.svg
    materialsvg/error.svg
    materialsvg/euro-symbol.svg
    materialsvg/event-available.svg
    materialsvg/event-busy.svg
    materialsvg/event-note.svg
    materialsvg/event-seat.svg
    materialsvg/event.svg
    materialsvg/ev-station.svg
    materialsvg/exit-to-app.svg
    materialsvg/expand-less.svg
    materialsvg/expand-more.svg
    materialsvg/explicit.svg
    materialsvg/explore.svg
    materialsvg/exposure-neg-1.svg
    materialsvg/exposure-neg-2.svg
    materialsvg/exposure-plus-1.svg
    materialsvg/exposure-plus-2.svg
    materialsvg/exposure.svg
    materialsvg/exposure-zero.svg
    materialsvg/extension.svg
    materialsvg/face.svg
    materialsvg/fast-forward.svg
    materialsvg/fast-rewind.svg
    materialsvg/favorite-border.svg
    materialsvg/favorite.svg
    materialsvg/featured-play-list.svg
    materialsvg/featured-video.svg
    materialsvg/feedback.svg
    materialsvg/fiber-dvr.svg
    materialsvg/fiber-manual-record.svg
    materialsvg/fiber-new.svg
    materialsvg/fiber-pin.svg
    materialsvg/fiber-smart-record.svg
    materialsvg/file-download.svg
    materialsvg/file-upload.svg
    materialsvg/filter-1.svg
    materialsvg/filter-2.svg
    materialsvg/filter-3.svg
    materialsvg/filter-4.svg
    materialsvg/filter-5.svg
    materialsvg/filter-6.svg
    materialsvg/filter-7.svg
    materialsvg/filter-8.svg
    materialsvg/filter-9-plus.svg
    materialsvg/filter-9.svg
    materialsvg/filter-b-and-w.svg
    materialsvg/filter-center-focus.svg
    materialsvg/filter-drama.svg
    materialsvg/filter-frames.svg
    materialsvg/filter-hdr.svg
    materialsvg/filter-list.svg
    materialsvg/filter-none.svg
    materialsvg/filter.svg
    materialsvg/filter-tilt-shift.svg
    materialsvg/filter-vintage.svg
    materialsvg/find-in-page.svg
    materialsvg/find-replace.svg
    materialsvg/fingerprint.svg
    materialsvg/first-page.svg
    materialsvg/fitness-center.svg
    materialsvg/flag.svg
    materialsvg/flare.svg
    materialsvg/flash-auto.svg
    materialsvg/flash-off.svg
    materialsvg/flash-on.svg
    materialsvg/flight-land.svg
    materialsvg/flight.svg
    materialsvg/flight-takeoff.svg
    materialsvg/flip.svg
    materialsvg/flip-to-back.svg
    materialsvg/flip-to-front.svg
    materialsvg/folder-open.svg
    materialsvg/folder-shared.svg
    materialsvg/folder-special.svg
    materialsvg/folder.svg
    materialsvg/format-align-center.svg
    materialsvg/format-align-justify.svg
    materialsvg/format-align-left.svg
    materialsvg/format-align-right.svg
    materialsvg/format-bold.svg
    materialsvg/format-clear.svg
    materialsvg/format-color-fill.svg
    materialsvg/format-color-reset.svg
    materialsvg/format-color-text.svg
    materialsvg/format-indent-decrease.svg
    materialsvg/format-indent-increase.svg
    materialsvg/format-italic.svg
    materialsvg/format-line-spacing.svg
    materialsvg/format-list-bulleted.svg
    materialsvg/format-list-numbered.svg
    materialsvg/format-paint.svg
    materialsvg/format-quote.svg
    materialsvg/format-shapes.svg
    materialsvg/format-size.svg
    materialsvg/format-strikethrough.svg
    materialsvg/format-textdirection-l-to-r.svg
    materialsvg/format-textdirection-r-to-l.svg
    materialsvg/format-underlined.svg
    materialsvg/forum.svg
    materialsvg/forward-10.svg
    materialsvg/forward-30.svg
    materialsvg/forward-5.svg
    materialsvg/forward.svg
    materialsvg/free-breakfast.svg
    materialsvg/fullscreen-exit.svg
    materialsvg/fullscreen.svg
    materialsvg/functions.svg
    materialsvg/gamepad.svg
    materialsvg/games.svg
    materialsvg/gavel.svg
    materialsvg/gesture.svg
    materialsvg/get-app.svg
    materialsvg/golf-course.svg
    materialsvg/gps-fixed.svg
    materialsvg/gps-not-fixed.svg
    materialsvg/gps-off.svg
    materialsvg/grade.svg
    materialsvg/gradient.svg
    materialsvg/grain.svg
    materialsvg/graphic-eq.svg
    materialsvg/grid-off.svg
    materialsvg/grid-on.svg
    materialsvg/group-add.svg
    materialsvg/group.svg
    materialsvg/group-work.svg
    materialsvg/g-translate.svg
    materialsvg/hdr-off.svg
    materialsvg/hdr-on.svg
    materialsvg/hdr-strong.svg
    materialsvg/hdr-weak.svg
    materialsvg/headset-mic.svg
    materialsvg/headset.svg
    materialsvg/healing.svg
    materialsvg/hearing.svg
    materialsvg/help.svg
    materialsvg/highlight-off.svg
    materialsvg/highlight.svg
    materialsvg/high-quality.svg
    materialsvg/history.svg
    materialsvg/home.svg
    materialsvg/hotel.svg
    materialsvg/hot-tub.svg
    materialsvg/hourglass-empty.svg
    materialsvg/hourglass-full.svg
    materialsvg/https.svg
    materialsvg/http.svg
    materialsvg/image-aspect-ratio.svg
    materialsvg/image.svg
    materialsvg/important-devices.svg
    materialsvg/import-contacts.svg
    materialsvg/import-export.svg
    materialsvg/inbox.svg
    materialsvg/info-outline.svg
    materialsvg/info.svg
    materialsvg/input.svg
    materialsvg/insert-chart.svg
    materialsvg/insert-comment.svg
    materialsvg/insert-drive-file.svg
    materialsvg/insert-emoticon.svg
    materialsvg/insert-invitation.svg
    materialsvg/insert-link.svg
    materialsvg/insert-photo.svg
    materialsvg/invert-colors-off.svg
    materialsvg/invert-colors.svg
    materialsvg/iso.svg
    materialsvg/keyboard-arrow-down.svg
    materialsvg/keyboard-arrow-left.svg
    materialsvg/keyboard-arrow-right.svg
    materialsvg/keyboard-arrow-up.svg
    materialsvg/keyboard-backspace.svg
    materialsvg/keyboard-capslock.svg
    materialsvg/keyboard-hide.svg
    materialsvg/keyboard-return.svg
    materialsvg/keyboard.svg
    materialsvg/keyboard-tab.svg
    materialsvg/keyboard-voice.svg
    materialsvg/kitchen.svg
    materialsvg/label-outline.svg
    materialsvg/label.svg
    materialsvg/landscape.svg
    materialsvg/language.svg
    materialsvg/laptop-chromebook.svg
    materialsvg/laptop-mac.svg
    materialsvg/laptop.svg
    materialsvg/laptop-windows.svg
    materialsvg/last-page.svg
    materialsvg/launch.svg
    materialsvg/layers-clear.svg
    materialsvg/layers.svg
    materialsvg/leak-add.svg
    materialsvg/leak-remove.svg
    materialsvg/lens.svg
    materialsvg/library-add.svg
    materialsvg/library-books.svg
    materialsvg/library-music.svg
    materialsvg/lightbulb-outline.svg
    materialsvg/linear-scale.svg
    materialsvg/line-style.svg
    materialsvg/line-weight.svg
    materialsvg/linked-camera.svg
    materialsvg/link.svg
    materialsvg/list.svg
    materialsvg/live-help.svg
    materialsvg/live-tv.svg
    materialsvg/local-activity.svg
    materialsvg/local-airport.svg
    materialsvg/local-atm.svg
    materialsvg/local-bar.svg
    materialsvg/local-cafe.svg
    materialsvg/local-car-wash.svg
    materialsvg/local-convenience-store.svg
    materialsvg/local-dining.svg
    materialsvg/local-drink.svg
    materialsvg/local-florist.svg
    materialsvg/local-gas-station.svg
    materialsvg/local-grocery-store.svg
    materialsvg/local-hospital.svg
    materialsvg/local-hotel.svg
    materialsvg/local-laundry-service.svg
    materialsvg/local-library.svg
    materialsvg/local-mall.svg
    materialsvg/local-movies.svg
    materialsvg/local-offer.svg
    materialsvg/local-parking.svg
    materialsvg/local-pharmacy.svg
    materialsvg/local-phone.svg
    materialsvg/local-pizza.svg
    materialsvg/local-play.svg
    materialsvg/local-post-office.svg
    materialsvg/local-printshop.svg
    materialsvg/local-see.svg
    materialsvg/local-shipping.svg
    materialsvg/local-taxi.svg
    materialsvg/location-city.svg
    materialsvg/location-disabled.svg
    materialsvg/location-off.svg
    materialsvg/location-on.svg
    materialsvg/location-searching.svg
    materialsvg/lock-open.svg
    materialsvg/lock-outline.svg
    materialsvg/lock.svg
    materialsvg/looks-3.svg
    materialsvg/looks-4.svg
    materialsvg/looks-5.svg
    materialsvg/looks-6.svg
    materialsvg/looks-one.svg
    materialsvg/looks.svg
    materialsvg/looks-two.svg
    materialsvg/loop.svg
    materialsvg/loupe.svg
    materialsvg/low-priority.svg
    materialsvg/loyalty.svg
    materialsvg/mail-outline.svg
    materialsvg/mail.svg
    materialsvg/map.svg
    materialsvg/markunread-mailbox.svg
    materialsvg/markunread.svg
    materialsvg/memory.svg
    materialsvg/menu.svg
    materialsvg/merge-type.svg
    materialsvg/message.svg
    materialsvg/mic-none.svg
    materialsvg/mic-off.svg
    materialsvg/mic.svg
    materialsvg/mms.svg
    materialsvg/mode-comment.svg
    materialsvg/mode-edit.svg
    materialsvg/monetization-on.svg
    materialsvg/monochrome-photos.svg
    materialsvg/mood-bad.svg
    materialsvg/mood.svg
    materialsvg/more-horiz.svg
    materialsvg/more.svg
    materialsvg/more-vert.svg
    materialsvg/motorcycle.svg
    materialsvg/mouse.svg
    materialsvg/move-to-inbox.svg
    materialsvg/movie-creation.svg
    materialsvg/movie-filter.svg
    materialsvg/movie.svg
    materialsvg/multiline-chart.svg
    materialsvg/music-note.svg
    materialsvg/music-video.svg
    materialsvg/my-location.svg
    materialsvg/nature-people.svg
    materialsvg/nature.svg
    materialsvg/navigate-before.svg
    materialsvg/navigate-next.svg
    materialsvg/navigation.svg
    materialsvg/near-me.svg
    materialsvg/network-cell.svg
    materialsvg/network-check.svg
    materialsvg/network-locked.svg
    materialsvg/network-wifi.svg
    materialsvg/new-releases.svg
    materialsvg/next-week.svg
    materialsvg/nfc.svg
    materialsvg/no-encryption.svg
    materialsvg/no-sim.svg
    materialsvg/note-add.svg
    materialsvg/note.svg
    materialsvg/notifications-active.svg
    materialsvg/notifications-none.svg
    materialsvg/notifications-off.svg
    materialsvg/notifications-paused.svg
    materialsvg/notifications.svg
    materialsvg/not-interested.svg
    materialsvg/ondemand-video.svg
    materialsvg/opacity.svg
    materialsvg/open-in-browser.svg
    materialsvg/open-in-new.svg
    materialsvg/open-with.svg
    materialsvg/pages.svg
    materialsvg/pageview.svg
    materialsvg/palette.svg
    materialsvg/panorama-fish-eye.svg
    materialsvg/panorama-horizontal.svg
    materialsvg/panorama.svg
    materialsvg/panorama-vertical.svg
    materialsvg/panorama-wide-angle.svg
    materialsvg/pan-tool.svg
    materialsvg/party-mode.svg
    materialsvg/pause-circle-filled.svg
    materialsvg/pause-circle-outline.svg
    materialsvg/pause.svg
    materialsvg/payment.svg
    materialsvg/people-outline.svg
    materialsvg/people.svg
    materialsvg/perm-camera-mic.svg
    materialsvg/perm-contact-calendar.svg
    materialsvg/perm-data-setting.svg
    materialsvg/perm-device-information.svg
    materialsvg/perm-identity.svg
    materialsvg/perm-media.svg
    materialsvg/perm-phone-msg.svg
    materialsvg/perm-scan-wifi.svg
    materialsvg/person-add.svg
    materialsvg/personal-video.svg
    materialsvg/person-outline.svg
    materialsvg/person-pin-circle.svg
    materialsvg/person-pin.svg
    materialsvg/person.svg
    materialsvg/pets.svg
    materialsvg/phone-android.svg
    materialsvg/phone-bluetooth-speaker.svg
    materialsvg/phone-forwarded.svg
    materialsvg/phone-in-talk.svg
    materialsvg/phone-iphone.svg
    materialsvg/phonelink-off.svg
    materialsvg/phonelink.svg
    materialsvg/phone-locked.svg
    materialsvg/phone-missed.svg
    materialsvg/phone-paused.svg
    materialsvg/phone.svg
    materialsvg/photo-album.svg
    materialsvg/photo-camera.svg
    materialsvg/photo-filter.svg
    materialsvg/photo-library.svg
    materialsvg/photo.svg
    materialsvg/picture-as-pdf.svg
    materialsvg/picture-in-picture-alt.svg
    materialsvg/picture-in-picture.svg
    materialsvg/pie-chart-outlined.svg
    materialsvg/pie-chart.svg
    materialsvg/pin-drop.svg
    materialsvg/place.svg
    materialsvg/play-arrow.svg
    materialsvg/play-circle-filled.svg
    materialsvg/play-circle-filled-white.svg
    materialsvg/play-circle-outline.svg
    materialsvg/play-for-work.svg
    materialsvg/playlist-add-check.svg
    materialsvg/playlist-add.svg
    materialsvg/playlist-play.svg
    materialsvg/plus-one.svg
    materialsvg/poll.svg
    materialsvg/polymer.svg
    materialsvg/pool.svg
    materialsvg/portable-wifi-off.svg
    materialsvg/portrait.svg
    materialsvg/power-input.svg
    materialsvg/power-settings-new.svg
    materialsvg/power.svg
    materialsvg/pregnant-woman.svg
    materialsvg/present-to-all.svg
    materialsvg/print.svg
    materialsvg/priority-high.svg
    materialsvg/public.svg
    materialsvg/publish.svg
    materialsvg/query-builder.svg
    materialsvg/question-answer.svg
    materialsvg/queue-music.svg
    materialsvg/queue-play-next.svg
    materialsvg/queue.svg
    materialsvg/radio-button-checked.svg
    materialsvg/radio-button-unchecked.svg
    materialsvg/radio.svg
    materialsvg/rate-review.svg
    materialsvg/receipt.svg
    materialsvg/recent-actors.svg
    materialsvg/record-voice-over.svg
    materialsvg/redeem.svg
    materialsvg/redo.svg
    materialsvg/refresh.svg
    materialsvg/remove-circle-outline.svg
    materialsvg/remove-circle.svg
    materialsvg/remove-from-queue.svg
    materialsvg/remove-red-eye.svg
    materialsvg/remove-shopping-cart.svg
    materialsvg/remove.svg
    materialsvg/repeat-one.svg
    materialsvg/repeat.svg
    materialsvg/replay-10.svg
    materialsvg/replay-30.svg
    materialsvg/replay-5.svg
    materialsvg/replay.svg
    materialsvg/reply-all.svg
    materialsvg/reply.svg
    materialsvg/report-problem.svg
    materialsvg/report.svg
    materialsvg/restaurant-menu.svg
    materialsvg/restaurant.svg
    materialsvg/restore-page.svg
    materialsvg/restore.svg
    materialsvg/ring-volume.svg
    materialsvg/room-service.svg
    materialsvg/room.svg
    materialsvg/rotate-90-degrees-ccw.svg
    materialsvg/rotate-left.svg
    materialsvg/rotate-right.svg
    materialsvg/rounded-corner.svg
    materialsvg/router.svg
    materialsvg/rowing.svg
    materialsvg/rss-feed.svg
    materialsvg/rv-hookup.svg
    materialsvg/satellite.svg
    materialsvg/save.svg
    materialsvg/scanner.svg
    materialsvg/schedule.svg
    materialsvg/school.svg
    materialsvg/screen-lock-landscape.svg
    materialsvg/screen-lock-portrait.svg
    materialsvg/screen-lock-rotation.svg
    materialsvg/screen-rotation.svg
    materialsvg/screen-share.svg
    materialsvg/sd-card.svg
    materialsvg/sd-storage.svg
    materialsvg/search.svg
    materialsvg/security.svg
    materialsvg/select-all.svg
    materialsvg/send.svg
    materialsvg/sentiment-dissatisfied.svg
    materialsvg/sentiment-neutral.svg
    materialsvg/sentiment-satisfied.svg
    materialsvg/sentiment-very-dissatisfied.svg
    materialsvg/sentiment-very-satisfied.svg
    materialsvg/settings-applications.svg
    materialsvg/settings-backup-restore.svg
    materialsvg/settings-bluetooth.svg
    materialsvg/settings-brightness.svg
    materialsvg/settings-cell.svg
    materialsvg/settings-ethernet.svg
    materialsvg/settings-input-antenna.svg
    materialsvg/settings-input-component.svg
    materialsvg/settings-input-composite.svg
    materialsvg/settings-input-hdmi.svg
    materialsvg/settings-input-svideo.svg
    materialsvg/settings-overscan.svg
    materialsvg/settings-phone.svg
    materialsvg/settings-power.svg
    materialsvg/settings-remote.svg
    materialsvg/settings.svg
    materialsvg/settings-system-daydream.svg
    materialsvg/settings-voice.svg
    materialsvg/share.svg
    materialsvg/shopping-basket.svg
    materialsvg/shopping-cart.svg
    materialsvg/shop.svg
    materialsvg/shop-two.svg
    materialsvg/short-text.svg
    materialsvg/show-chart.svg
    materialsvg/shuffle.svg
    materialsvg/signal-cellular-0-bar.svg
    materialsvg/signal-cellular-1-bar.svg
    materialsvg/signal-cellular-2-bar.svg
    materialsvg/signal-cellular-3-bar.svg
    materialsvg/signal-cellular-4-bar.svg
    materialsvg/signal-cellular-connected-no-internet-0_bar.svg
    materialsvg/signal-cellular-connected-no-internet-1_bar.svg
    materialsvg/signal-cellular-connected-no-internet-2_bar.svg
    materialsvg/signal-cellular-connected-no-internet-3_bar.svg
    materialsvg/signal-cellular-connected-no-internet-4_bar.svg
    materialsvg/signal-cellular-no-sim.svg
    materialsvg/signal-cellular-null.svg
    materialsvg/signal-cellular-off.svg
    materialsvg/signal-wifi-0-bar.svg
    materialsvg/signal-wifi-1-bar-lock.svg
    materialsvg/signal-wifi-1-bar.svg
    materialsvg/signal-wifi-2-bar-lock.svg
    materialsvg/signal-wifi-2-bar.svg
    materialsvg/signal-wifi-3-bar-lock.svg
    materialsvg/signal-wifi-3-bar.svg
    materialsvg/signal-wifi-4-bar-lock.svg
    materialsvg/signal-wifi-4-bar.svg
    materialsvg/signal-wifi-off.svg
    materialsvg/sim-card-alert.svg
    materialsvg/sim-card.svg
    materialsvg/skip-next.svg
    materialsvg/skip-previous.svg
    materialsvg/slideshow.svg
    materialsvg/slow-motion-video.svg
    materialsvg/smartphone.svg
    materialsvg/smoke-free.svg
    materialsvg/smoking-rooms.svg
    materialsvg/sms-failed.svg
    materialsvg/sms.svg
    materialsvg/snooze.svg
    materialsvg/sort.svg
    materialsvg/space-bar.svg
    materialsvg/spa.svg
    materialsvg/speaker-group.svg
    materialsvg/speaker-notes-off.svg
    materialsvg/speaker-notes.svg
    materialsvg/speaker-phone.svg
    materialsvg/speaker.svg
    materialsvg/spellcheck.svg
    materialsvg/star-half.svg
    materialsvg/stars.svg
    materialsvg/stay-current-landscape.svg
    materialsvg/stay-current-portrait.svg
    materialsvg/stay-primary-landscape.svg
    materialsvg/stay-primary-portrait.svg
    materialsvg/stop-screen-share.svg
    materialsvg/stop.svg
    materialsvg/storage.svg
    materialsvg/store-mall-directory.svg
    materialsvg/store.svg
    materialsvg/straighten.svg
    materialsvg/streetview.svg
    materialsvg/strikethrough-s.svg
    materialsvg/style.svg
    materialsvg/subdirectory-arrow-left.svg
    materialsvg/subdirectory-arrow-right.svg
    materialsvg/subject.svg
    materialsvg/subscriptions.svg
    materialsvg/subtitles.svg
    materialsvg/subway.svg
    materialsvg/supervisor-account.svg
    materialsvg/surround-sound.svg
    materialsvg/swap-calls.svg
    materialsvg/swap-horiz.svg
    materialsvg/swap-vertical-circle.svg
    materialsvg/swap-vert.svg
    materialsvg/switch-camera.svg
    materialsvg/switch-video.svg
    materialsvg/sync-disabled.svg
    materialsvg/sync-problem.svg
    materialsvg/sync.svg
    materialsvg/system-update-alt.svg
    materialsvg/system-update.svg
    materialsvg/tablet-android.svg
    materialsvg/tablet-mac.svg
    materialsvg/tablet.svg
    materialsvg/tab.svg
    materialsvg/tab-unselected.svg
    materialsvg/tag-faces.svg
    materialsvg/tap-and-play.svg
    materialsvg/terrain.svg
    materialsvg/text-fields.svg
    materialsvg/text-format.svg
    materialsvg/textsms.svg
    materialsvg/texture.svg
    materialsvg/theaters.svg
    materialsvg/thumb-down.svg
    materialsvg/thumbs-up-down.svg
    materialsvg/thumb-up.svg
    materialsvg/timelapse.svg
    materialsvg/timeline.svg
    materialsvg/timer-10.svg
    materialsvg/timer-3.svg
    materialsvg/timer-off.svg
    materialsvg/timer.svg
    materialsvg/time-to-leave.svg
    materialsvg/title.svg
    materialsvg/toc.svg
    materialsvg/today.svg
    materialsvg/toll.svg
    materialsvg/tonality.svg
    materialsvg/touch-app.svg
    materialsvg/toys.svg
    materialsvg/track-changes.svg
    materialsvg/traffic.svg
    materialsvg/train.svg
    materialsvg/tram.svg
    materialsvg/transfer-within-a-station.svg
    materialsvg/transform.svg
    materialsvg/translate.svg
    materialsvg/trending-down.svg
    materialsvg/trending-flat.svg
    materialsvg/trending-up.svg
    materialsvg/tune.svg
    materialsvg/turned-in-not.svg
    materialsvg/turned-in.svg
    materialsvg/tv.svg
    materialsvg/unarchive.svg
    materialsvg/undo.svg
    materialsvg/unfold-less.svg
    materialsvg/unfold-more.svg
    materialsvg/update.svg
    materialsvg/usb.svg
    materialsvg/verified-user.svg
    materialsvg/vertical-align-bottom.svg
    materialsvg/vertical-align-center.svg
    materialsvg/vertical-align-top.svg
    materialsvg/vibration.svg
    materialsvg/video-call.svg
    materialsvg/videocam-off.svg
    materialsvg/videocam.svg
    materialsvg/videogame-asset.svg
    materialsvg/video-label.svg
    materialsvg/video-library.svg
    materialsvg/view-agenda.svg
    materialsvg/view-array.svg
    materialsvg/view-carousel.svg
    materialsvg/view-column.svg
    materialsvg/view-comfy.svg
    materialsvg/view-compact.svg
    materialsvg/view-day.svg
    materialsvg/view-headline.svg
    materialsvg/view-list.svg
    materialsvg/view-module.svg
    materialsvg/view-quilt.svg
    materialsvg/view-stream.svg
    materialsvg/view-week.svg
    materialsvg/visibility-off.svg
    materialsvg/visibility.svg
    materialsvg/voice-chat.svg
    materialsvg/voicemail.svg
    materialsvg/volume-down.svg
    materialsvg/volume-mute.svg
    materialsvg/volume-off.svg
    materialsvg/volume-up.svg
    materialsvg/vpn-key.svg
    materialsvg/vpn-lock.svg
    materialsvg/wallpaper.svg
    materialsvg/warning.svg
    materialsvg/watch-later.svg
    materialsvg/watch.svg
    materialsvg/wb-auto.svg
    materialsvg/wb-cloudy.svg
    materialsvg/wb-incandescent.svg
    materialsvg/wb-iridescent.svg
    materialsvg/wb-sunny.svg
    materialsvg/wc.svg
    materialsvg/web-asset.svg
    materialsvg/web.svg
    materialsvg/weekend.svg
    materialsvg/whatshot.svg
    materialsvg/widgets.svg
    materialsvg/wifi-lock.svg
    materialsvg/wifi.svg
    materialsvg/wifi-tethering.svg
    materialsvg/work.svg
    materialsvg/wrap-text.svg
    materialsvg/youtube-searched-for.svg
    materialsvg/zoom-out-map.svg
)
